# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: stuff by danvet
email: daniel.vetter@ffwll.ch
description: > # this means to ignore newlines until "baseurl:"
  Daniel Vetter's ramblings on code, bugs, graphics, hw and the utter lack of
  sanity in all this.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: danvet
github_username:  danvet
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
